const mongoose = require("mongoose");
const productSchema = new mongoose.Schema({
  Product_images: [
    {
      images: String,
    },
  ],
  User_Id: String,
  Post_type: String,
  tittle: String,
  description: String,
  quantity: String,
  Currency: String,
  Rented_as: String,
  Rented_Price: String,
  Taxes: String,
  Service_fee: String,
  Category: String,
  Sub_Category: String,
  Brand: String,
  Vendor_Name: String,
  Vendor_street: String,
  Vendor_Phone: String,
  Vendor_Description: String,
  Vendor_Postcode: String,
  Vendor_Country: String,
  Vendor_City: String,
  Payment_Deposit: String,
  Rented_Amount_per: String,
  Payment_Amount: String,
  ProductDetails_Description: String,
  AboutProduct_Description: String,
  Things_Description: String,
  Cancel_Description: String,
  customDetails: [
    {
      label: String,
      value: String,
    },
  ],
  Listing_Street_No1: String,
  Listing_Street_No2: String,
  Listing_Poscode: String,
  Listing_City: String,
  Listing_Country: String,
  Listing_Latitude: String,
  Listing_Longitude: String,
  Booking_Selected: String,
  Booked_date: [String],
  Push_up_Plan: String,
  Highlight: String,
  Top_Plan: String,
});
const ProductModel = mongoose.model("Products", productSchema);
module.exports = ProductModel;
